//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX5U_IOMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double COSValue {
            get {
                return ((double)(this["COSValue"]));
            }
            set {
                this["COSValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TW")]
        public string LanguageSetting {
            get {
                return ((string)(this["LanguageSetting"]));
            }
            set {
                this["LanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webform@mechalogix.com")]
        public string senderEmail {
            get {
                return ((string)(this["senderEmail"]));
            }
            set {
                this["senderEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jvvswkymcyokcvug")]
        public string senderPassword {
            get {
                return ((string)(this["senderPassword"]));
            }
            set {
                this["senderPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Gmail_SMTP_server {
            get {
                return ((string)(this["Gmail_SMTP_server"]));
            }
            set {
                this["Gmail_SMTP_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public int TLS_port {
            get {
                return ((int)(this["TLS_port"]));
            }
            set {
                this["TLS_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Gmail_SMTP_server1 {
            get {
                return ((string)(this["Gmail_SMTP_server1"]));
            }
            set {
                this["Gmail_SMTP_server1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan userDefinedNotifyTime {
            get {
                return ((global::System.TimeSpan)(this["userDefinedNotifyTime"]));
            }
            set {
                this["userDefinedNotifyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Metric")]
        public string UnitSetting {
            get {
                return ((string)(this["UnitSetting"]));
            }
            set {
                this["UnitSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5e3yIPf5bcbSJh4ebTs45xAgRsCKj6oj9M8GsCIOMbp4Oadrv1YZpt7WsY1kqk4AXmz8nfGzC9tRH8Kvg" +
            "mQWsXu0AXWh5BiMiJ6FU+YqeOi9duMvYv5yiLMAmlqxkFyvhT5ZwREsBVY/xuYIU05EyAdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string LineAccessToken {
            get {
                return ((string)(this["LineAccessToken"]));
            }
            set {
                this["LineAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LineImagePath {
            get {
                return ((string)(this["LineImagePath"]));
            }
            set {
                this["LineImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NotifyTime {
            get {
                return ((global::System.DateTime)(this["NotifyTime"]));
            }
            set {
                this["NotifyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Last_cloudupdatetime {
            get {
                return ((global::System.DateTime)(this["Last_cloudupdatetime"]));
            }
            set {
                this["Last_cloudupdatetime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultUtilizationRate {
            get {
                return ((int)(this["DefaultUtilizationRate"]));
            }
            set {
                this["DefaultUtilizationRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationStart1 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationStart1"]));
            }
            set {
                this["UtilizationStart1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationStart2 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationStart2"]));
            }
            set {
                this["UtilizationStart2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationStart3 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationStart3"]));
            }
            set {
                this["UtilizationStart3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationStart4 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationStart4"]));
            }
            set {
                this["UtilizationStart4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationEnd1 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationEnd1"]));
            }
            set {
                this["UtilizationEnd1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationEnd2 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationEnd2"]));
            }
            set {
                this["UtilizationEnd2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationEnd3 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationEnd3"]));
            }
            set {
                this["UtilizationEnd3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan UtilizationEnd4 {
            get {
                return ((global::System.TimeSpan)(this["UtilizationEnd4"]));
            }
            set {
                this["UtilizationEnd4"] = value;
            }
        }
    }
}
