//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX5U_IOMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double COSValue {
            get {
                return ((double)(this["COSValue"]));
            }
            set {
                this["COSValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TW")]
        public string LanguageSetting {
            get {
                return ((string)(this["LanguageSetting"]));
            }
            set {
                this["LanguageSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webform@mechalogix.com")]
        public string senderEmail {
            get {
                return ((string)(this["senderEmail"]));
            }
            set {
                this["senderEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jvvswkymcyokcvug")]
        public string senderPassword {
            get {
                return ((string)(this["senderPassword"]));
            }
            set {
                this["senderPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Gmail_SMTP_server {
            get {
                return ((string)(this["Gmail_SMTP_server"]));
            }
            set {
                this["Gmail_SMTP_server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public int TLS_port {
            get {
                return ((int)(this["TLS_port"]));
            }
            set {
                this["TLS_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string Gmail_SMTP_server1 {
            get {
                return ((string)(this["Gmail_SMTP_server1"]));
            }
            set {
                this["Gmail_SMTP_server1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan userDefinedNotifyTime {
            get {
                return ((global::System.TimeSpan)(this["userDefinedNotifyTime"]));
            }
            set {
                this["userDefinedNotifyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Metric")]
        public string UnitSetting {
            get {
                return ((string)(this["UnitSetting"]));
            }
            set {
                this["UnitSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WpbFYDIBinzTU96hCVd3xpD7/R9iLp/Hnc3x2hzHJw4WUX2oNmF5CZi0OLczDUoFL5GJ574uHkaeuRUPr" +
            "jd9CyfUqArCCbwSm2jPPKxkWCwdFOlfvnXfVp2S5EaW/4j9xPAHwWOBiAOYD0v1SAV5xgdB04t89/1O/" +
            "w1cDnyilFU=")]
        public string LineAccessToken {
            get {
                return ((string)(this["LineAccessToken"]));
            }
            set {
                this["LineAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LineImagePath {
            get {
                return ((string)(this["LineImagePath"]));
            }
            set {
                this["LineImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime NotifyTime {
            get {
                return ((global::System.DateTime)(this["NotifyTime"]));
            }
            set {
                this["NotifyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Last_cloudupdatetime {
            get {
                return ((global::System.DateTime)(this["Last_cloudupdatetime"]));
            }
            set {
                this["Last_cloudupdatetime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DefaultUtilizationRate {
            get {
                return ((int)(this["DefaultUtilizationRate"]));
            }
            set {
                this["DefaultUtilizationRate"] = value;
            }
        }
    }
}
